{% set name = "torchsparse" %}
{% set number = 7 %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mit-han-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a1cf3e8ecabb0f81cab7e14ed5ed0a31c8cb62b73d8ae172c50a779a82aae640

build:
  number: {{ number }}
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != 'None']
    - pytorch-cpu  # [cuda_compiler_version == 'None' and build_platform != target_platform]
    - pytorch-gpu  # [cuda_compiler_version != 'None' and build_platform != target_platform]
  host:
    - python
    - pip
    - sparsehash
    - pytorch-cpu  # [cuda_compiler_version == 'None']
    - pytorch-gpu  # [cuda_compiler_version != 'None']
  run:
    - python
    - pytorch-cpu  # [cuda_compiler_version == 'None']
    - pytorch-gpu  # [cuda_compiler_version != 'None']

test:
  imports:
    - {{ name }}
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mit-han-lab/torchsparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A high-performance computing library for efficient 3D sparse convolution.
  description: |
    A high-performance computing library for efficient 3D sparse convolution.
  dev_url: https://github.com/mit-han-lab/{{ name }}

extra:
  recipe-maintainers:
    - benjaminrwilson
