{% set name = "torchsparse" %}
{% set number = 8 %}
{% set version = "1.4.0" %}

# waiting for https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1890
{% set pytorch_version = "1.10.0" %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mit-han-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a1cf3e8ecabb0f81cab7e14ed5ed0a31c8cb62b73d8ae172c50a779a82aae640

build:
  number: {{ number }}
  skip: true  # [win or osx]
  build:
    string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torch_proc_type }}  # [cuda_compiler_version == "None"]
    string: py{{ CONDA_PY }}cuda{{ cuda_compiler_version|replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torch_proc_type }}  # [cuda_compiler_version != "None"]
    run_exports:
      # ensure matching proc-type
      - torchvision =*=*_{{ torch_proc_type }}

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != 'None']
    - sysroot_linux-64 ==2.17  # [linux64]
    - pytorch ={{ pytorch_version }}={{ torch_proc_type }}*  # [build_platform != target_platform]
  host:
    - python
    - pip
    - sparsehash
    - pytorch {{ pytorch_version }}
    - pytorch-cpu  # [cuda_compiler_version == "None"]
    - pytorch-gpu  # [cuda_compiler_version != "None"]
  run:
    - python
    - pytorch-cpu  # [cuda_compiler_version == "None"]
    - pytorch-gpu  # [cuda_compiler_version != "None"]

test:
  imports:
    - {{ name }}
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mit-han-lab/torchsparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A high-performance computing library for efficient 3D sparse convolution.
  description: |
    A high-performance computing library for efficient 3D sparse convolution.
  dev_url: https://github.com/mit-han-lab/{{ name }}

extra:
  recipe-maintainers:
    - benjaminrwilson
