{% set name = "torchsparse" %}
{% set number = 8 %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mit-han-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a1cf3e8ecabb0f81cab7e14ed5ed0a31c8cb62b73d8ae172c50a779a82aae640

build:
  number: {{ number }}
  skip: true  # [win or pytorch == "1.9.*" and cuda_compiler_version == "11.0" or pytorch == "1.8.*" and cuda_compiler_version == "11.0" or pytorch == "1.7.*" and cuda_compiler_version != "10.2"]

  string: torch{{ pytorch | replace('.', '') | replace('*', '') }}_cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: torch{{ pytorch | replace('.', '') | replace('*', '') }}_cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}       


requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != 'None']
    - pytorch-cpu  # [cuda_compiler_version == 'None' and build_platform != target_platform]
    - pytorch-gpu  # [cuda_compiler_version != 'None' and build_platform != target_platform]
  host:
    - python
    - pip
    - sparsehash
    - pytorch-cpu {{ pytorch }}  # [cuda_compiler_version == "None"]
    - pytorch-gpu {{ pytorch }}  # [cuda_compiler_version != "None"]
  run:
    - python
    - {{ pin_compatible('pytorch-cpu', min_pin='x.x.x', max_pin='x.x') }}  # [cuda_compiler_version == "None"]
    - {{ pin_compatible('pytorch-gpu', min_pin='x.x.x', max_pin='x.x') }}  # [cuda_compiler_version != "None"]

test:
  imports:
    - {{ name }}
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mit-han-lab/torchsparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A high-performance computing library for efficient 3D sparse convolution.
  description: |
    A high-performance computing library for efficient 3D sparse convolution.
  dev_url: https://github.com/mit-han-lab/{{ name }}

extra:
  recipe-maintainers:
    - benjaminrwilson
