{% set name = "torchsparse" %}
{% set version = "1.4.0" %}

# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mit-han-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a1cf3e8ecabb0f81cab7e14ed5ed0a31c8cb62b73d8ae172c50a779a82aae640

build:
  number: 14
  skip: true  # [win]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torch_proc_type }}  # [cuda_compiler_version == "None"]
  string: py{{ CONDA_PY }}cuda{{ cuda_compiler_version|replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torch_proc_type }}  # [cuda_compiler_version != "None"]
  run_exports:
    # ensure matching proc-type
    - torchvision =*=*_{{ torch_proc_type }}

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != 'None']
    - sysroot_linux-64 ==2.17  # [linux64]
    - pytorch
    - pytorch ={{ pytorch }}={{ torch_proc_type }}*
  host:
    - python
    - pip
    - sparsehash
    # Leaving two dependencies helps rerender correctly
    # The first gets filled in by the global pinnings
    # The second gets the processor type
    - pytorch
    - pytorch =*={{ torch_proc_type }}*
  run:
    - python
  run_constrained:
    # 2022/02/05 hmaarrfk
    # While conda packaging seems to allow us to specify
    # constraints on the same package in different lines
    # the resulting package doesn't have the ability to
    # be specified in multiples lines
    # This makes it tricky to use run_exports
    # we add the GPU constraint in the run_constrained
    # to allow us to have "two" constraints on the
    # running package
    - pytorch =*={{ torch_proc_type }}*

test:
  imports:
    - torchsparse
    - torchsparse.backend
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mit-han-lab/torchsparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A high-performance computing library for efficient 3D sparse convolution.
  description: |
    A high-performance computing library for efficient 3D sparse convolution.
  dev_url: https://github.com/mit-han-lab/{{ name }}

extra:
  recipe-maintainers:
    - benjaminrwilson
